pipeline {
    agent any 

    parameters{
        choice(name: 'terraformAction', choices: ['Apply', 'Destroy'], description: 'Choose your terraform action')
    }

    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID') 
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages{

        stage('check out') {
            steps{
                script{
                    dir("trfm-iac"){
                        git url: 'https://github.com/krrg14/chatbot-project.git', branch: 'EKS'
                    }
                }
            }
        }

        stage('plan') {
            steps{
                sh 'pwd; cd EKS/; terraform init'
                sh 'pwd; cd EKS/; terraform plan -out tfplan'
                sh 'pwd; cd EKS/; terraform show -no-color tfplan > tfplan.txt'
            }
        }

        stage('Apply'){
            when{
                expression {
                    return params.terraformAction == 'Apply'
                }
            }
            steps{
                sh 'pwd; cd EKS/; terraform apply tfplan '
            }
        }

        stage('Destroy'){
            when{
                expression {
                    return params.terraformAction == 'Destroy'
                }
            }
            steps{
                sh 'pwd; cd EKS/; terraform destroy --auto-approve'
            }
        }

        stage('backend stage') {
            steps{
                sh '''
                    pwd
                    cd EKS/
                    aws s3 cp *.tfstate s3://unuesd-delete-volumes-bucket/eks/
                '''
            }
        }

    }
}