apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatbot
  name: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - image: krrg14/chatbot:e3d62ec32b41c7e05d2e90603dc9c021a1e0e824
        name: chatbot
        imagePullPolicy: Always
        ports: 
        - containerPort: 8501


---

apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: LoadBalancer
  selector:
    app: chatbot
  ports:
    - port: 80 
      targetPort: 8501
      protocol: TCP
